title: "Germán Molpeceres"
description: "Molecular Astrophysics, Astrochemistry"
baseurl: ""
url: "https://gmolpeceres.github.io"

markdown: kramdown
sass:
  style: compressed

permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins: []
